# Generated by Django 3.1.7 on 2021-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theames_text', models.CharField(help_text='Text of the theame', max_length=20)),
            ],
            options={
                'ordering': ['-theames_text'],
            },
        ),
    ]
