# Generated by Django 3.1.7 on 2021-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theames',
            new_name='Theame',
        ),
        migrations.AlterModelOptions(
            name='theame',
            options={'ordering': ['-theame_text']},
        ),
        migrations.RenameField(
            model_name='theame',
            old_name='theames_text',
            new_name='theame_text',
        ),
    ]
