# Generated by Django 3.1.7 on 2021-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210304_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='theame',
            name='theame_user',
            field=models.CharField(default=23, help_text='Username', max_length=16),
            preserve_default=False,
        ),
    ]
